'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const api=require('../raiox01/rx-batch.js');
const sid='11111111-1111-4111-8111-111111111111', token='22222222-2222-4222-8222-222222222222';
const event=(n,name='quiz_step_view')=>({event_id:`33333333-3333-4333-8333-${String(n).padStart(12,'0')}`,session_id:sid,sequence:n,test_mode:true,event_name:name,source:'quiz_raiox01',lancamento:'raiox01_2026_09',page_url:'https://quiz.brunosimplicio.com.br/raiox01/',properties:{},context:{},attribution:{},occurred_at:'2026-10-06T12:00:00Z'});
const ack=p=>({ok:true,stored:true,event_id:p.event_id,test_mode:p.test_mode,session_token:token,lead_created:p.event_name==='lead_submit',duplicate:false});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function harness(extra={}){
 let currentToken=extra.noToken?null:token; const store=new Map(),calls=[],confirmed=[],payloads=[],dedup=new Map();
 const options={sessionId:sid,testMode:true,forceTest:true,resumed:false,storage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},getToken:()=>currentToken,bootstrap:()=>event(1,'page_view'),allowed:()=>true,
  requestOne:async p=>{calls.push('single:'+p.sequence); currentToken=token;const a={...ack(p),duplicate:dedup.has(p.event_id)};dedup.set(p.event_id,p);confirmed.push(p.event_id);return a;},
  onStored:(p,a)=>{currentToken=a.session_token;confirmed.push(p.event_id);},
  fetch:async(_url,init)=>{const p=JSON.parse(init.body);payloads.push(p);calls.push('batch:'+p.events.map(e=>e.sequence).join(','));for(const e of p.events)dedup.set(e.event_id,e);return Response.json({ok:true,stored:true,atomic:true,batch_version:'rx01-batch-v1',test_mode:true,event_ids:p.events.map(e=>e.event_id),receipts:p.events.map(ack),session_token:token,quiz_status:null});},...extra};
 return {options,store,calls,confirmed,payloads,dedup,transport:api.create(options)};
}
test('coalesces already queued ordered events; each gets its own receipt',async()=>{const h=harness();const a=event(2),b=event(3,'lead_submit'),c=event(4);const r=await Promise.all([a,b,c].map(h.transport.enqueue));assert.deepEqual(h.calls,['batch:2,3,4']);assert.equal(r[0].lead_created,false);assert.equal(r[1].lead_created,true);assert.deepEqual(r.map(x=>x.event_id),[a,b,c].map(x=>x.event_id));assert.deepEqual(h.payloads[0].events,[a,b,c]);});
test('a single event is not delayed to fill a batch',async()=>{const h=harness();await h.transport.enqueue(event(2));assert.deepEqual(h.calls,['single:2']);});
test('never dispatches concurrently',async()=>{let active=0,max=0;const h=harness({requestOne:async p=>{active++;max=Math.max(max,active);await delay(15);active--;return ack(p);}});const first=h.transport.enqueue(event(2));await delay(2);const other=h.transport.enqueue(event(3));await Promise.all([first,other]);assert.equal(max,1);});
test('bootstrap is sent individually before batch, no fabricated token',async()=>{const h=harness({noToken:true});await Promise.all([h.transport.enqueue(event(1,'page_view')),h.transport.enqueue(event(2)),h.transport.enqueue(event(3))]);assert.deepEqual(h.calls,['single:1','batch:2,3']);});
test('each batch <=8 events, preserving whole order',async()=>{const h=harness();const events=Array.from({length:20},(_,i)=>event(i+2));await Promise.all(events.map(h.transport.enqueue));assert.deepEqual(h.payloads.flatMap(p=>p.events.map(e=>e.sequence)),events.map(e=>e.sequence));assert.ok(h.payloads.every(p=>p.events.length<=8));});
test('UTF8 byte bound prevents oversized keepalive groups',async()=>{const h=harness();const a={...event(2),properties:{value:'á'.repeat(8000)}},b={...event(3),properties:{value:'á'.repeat(8000)}};await Promise.all([a,b].map(h.transport.enqueue));assert.equal(h.payloads.length,0);assert.deepEqual(h.calls,['single:2','single:3']);});
test('pending duplicate ID returns the same promise without another write',async()=>{const h=harness();const p=event(2),a=h.transport.enqueue(p),b=h.transport.enqueue(p);assert.equal(a,b);await a;assert.equal(h.calls.length,1);});
test('same event ID with different contents is rejected',async()=>{const h=harness(),p=event(2),a=h.transport.enqueue(p);await assert.rejects(h.transport.enqueue({...p,properties:{altered:true}}),/payload_changed/);await a;});
test('HTTP rejection falls back to original singles without changing IDs',async()=>{const h=harness({fetch:async()=>Response.json({ok:false,stored:false},{status:503})});const events=[event(2),event(3)];await Promise.all(events.map(h.transport.enqueue));assert.deepEqual(h.confirmed,events.map(e=>e.event_id));assert.deepEqual(h.calls,['single:2','single:3']);assert.equal(h.transport.diagnostics().fallbacks,1);assert.equal(h.transport.diagnostics().active,false);});
test('ambiguous committed request is retried using the same IDs',async()=>{const h=harness();h.options.fetch=async(_url,init)=>{for(const p of JSON.parse(init.body).events)h.dedup.set(p.event_id,p);throw Error('response_lost');};const events=[event(2),event(3)];const a=await Promise.all(events.map(h.transport.enqueue));assert.ok(a.every(x=>x.duplicate));assert.equal(h.dedup.size,2);});
test('partial or reordered ACK cannot mark events as saved',async()=>{let called=0;const h=harness({onStored:()=>called++,fetch:async(_u,i)=>{const p=JSON.parse(i.body);return Response.json({ok:true,stored:true,atomic:true,batch_version:'rx01-batch-v1',test_mode:true,session_token:token,event_ids:p.events.map(e=>e.event_id).reverse(),receipts:p.events.map(ack),quiz_status:null});}});await Promise.all([event(2),event(3)].map(h.transport.enqueue));assert.equal(called,0);assert.equal(h.transport.diagnostics().fallbacks,1);});
test('single fallback failures are not turned into success',async()=>{const h=harness({fetch:async()=>{throw Error('offline');},requestOne:async()=>{throw Error('offline');}});const r=await Promise.allSettled([event(2),event(3)].map(h.transport.enqueue));assert.ok(r.every(x=>x.status==='rejected'));assert.equal(h.transport.diagnostics().confirmed,0);});
test('test mode mismatch is not accepted as an ACK',async()=>{const h=harness({fetch:async()=>Response.json({ok:true,stored:true,test_mode:false})});await Promise.all([event(2),event(3)].map(h.transport.enqueue));assert.equal(h.transport.diagnostics().fallbacks,1);});
test('increasing sequence is never rearranged to batch a retry',async()=>{const h=harness();await Promise.all([event(3),event(2)].map(h.transport.enqueue));assert.deepEqual(h.calls,['single:3','single:2']);});
test('optional events remain subject to consent at dispatch',async()=>{const h=harness({allowed:p=>p.event_name!=='rx_scroll'});const r=await Promise.all([event(2,'rx_scroll'),event(3)].map(h.transport.enqueue));assert.equal(r[0].skipped,true);assert.deepEqual(h.calls,['single:3']);});
test('existing legacy session is not enrolled, even after configuration changes',()=>{const h=harness({resumed:true});assert.equal(h.transport,null);});
test('storage unavailable conservatively keeps legacy',()=>{const h=harness({storage:{getItem:()=>{throw Error('blocked');}}});assert.equal(h.transport,null);});
test('production cannot force test enrollment',()=>{const h=harness({testMode:false,forceTest:true});assert.equal(h.transport,null);});
test('disabled defaults leave production unchanged',()=>{assert.equal(api.settings.enabled,false);assert.equal(api.settings.percent,0);const h=harness({testMode:false,forceTest:false});assert.equal(h.transport,null);});
test('no receipt resolves before the complete batch ACK',async()=>{let release;const gate=new Promise(r=>release=r);const h=harness();const original=h.options.fetch;h.options.fetch=async(...a)=>{await gate;return original(...a);};let resolved=0;const promises=[event(2),event(3)].map(p=>h.transport.enqueue(p).then(()=>resolved++));await delay(10);assert.equal(resolved,0);release();await Promise.all(promises);assert.equal(resolved,2);});
